# Generated by Django 2.1.4 on 2018-12-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customermodel_manufacturerverificationcodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='telephone_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
