# Generated by Django 2.1.4 on 2018-12-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userbankaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturermodel',
            old_name='representative',
            new_name='user',
        ),
        migrations.AddField(
            model_name='manufacturermodel',
            name='telephone_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
