# Generated by Django 2.1.4 on 2018-12-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181222_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
