# Generated by Django 2.1.4 on 2018-12-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181223_1000'),
        ('users', '0008_auto_20181222_1803'),
    ]

    operations = [
    ]
