# Generated by Django 2.1.4 on 2018-12-23 19:03

from django.db import migrations, models
import django.db.models.deletion
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=ecom.models.car_post_image_path)),
                ('car_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.CarPostModel')),
            ],
        ),
    ]
